### ISSUE TITLE
"Quote Threading" crashed on node Post No.66230885 (mu).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1002]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.12.0.8 crx
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36
URL: http://boards.4chan.org/mu/thread/66228217

ReferenceError: Set is not defined
at Post.QuoteThreading.node (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:21762:21)
    at Callbacks.execute (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:4676:17)
    at Object.Main.callbackNodes (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:22610:12)
    at Object.ThreadUpdater.parse (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:17031:14)
    at XMLHttpRequest.ThreadUpdater.cb.load (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:16819:27)

`<div class="postContainer replyContainer noFile" id="pc66230885" data-full-i-d="mu.66230885"><div id="sa66230885"><a class="hide-reply-button" href="javascript:;"><span class="fa fa-minus-square-o"></span></a></div><div id="p66230885" class="post reply"><div class="postInfo desktop" id="pi66230885"><input type="checkbox" name="66230885" value="delete"> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span class="dateTime" data-utc="1467894274">07/07/16(Thu)14:24:34</span> <span class="postNum desktop"><a href="#p66230885" title="Link to this post">No.</a><a href="javascript:quote('66230885');" title="Reply to this post">66230885</a></span><a class="menu-button" href="javascript:;"><i class="fa fa-angle-down"></i></a><span class="container"></span></div><blockquote class="postMessage" id="m66230885"><a href="#p66230823" class="quotelink">&gt;&gt;66230823</a><br>Djentheaven</blockquote></div></div>`

**Comment by ccd0** [comment]
Your browser is out of date and not supported by newer versions of 4chan X.

**Comment by ccd0** [comment]
These particular changes have been reverted for now, but you should still update your browser as soon as possible.
