### ISSUE TITLE
"Reply Hiding" crashed on node Post No.147947205 (vg).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1010]
Submitter: anu
Email: kakerlak@hotmail.com
Just installed the extension and went to a thread to test features, I was welcomed with multiple red banners across my screen. Previous versions had this issue too but not this bad. 

[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.12.1.4 crx
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
URL: http://boards.4chan.org/vg/thread/147946932

TypeError: Cannot read property 'firstChild' of null
at Post.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6757:27)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4676:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22685:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22689:16)
    at Object.callbackNodesDB (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22700:14)
    at Object.initThread (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22654:21)
    at initReady (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22599:21)
    at HTMLDocument.cb (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:3855:14)

`<div class="postContainer replyContainer" id="pc147947205" data-full-i-d="vg.147947205"><div id="sa147947205"><a class="hide-reply-button" href="javascript:;"><span class="fa fa-minus-square-o"></span></a></div><div id="p147947205" class="post reply"><div class="postInfoM mobile" id="pim147947205"><span class="nameBlock"><span class="name">Anonymous</span><br></span><span class="dateTime postNum" data-utc="1468092935">07/09/16(Sat)15:35:35 <a href="#p147947205" title="Link to this post">No.</a><a href="javascript:quote('147947205');" title="Reply to this post">147947205</a></span></div><div class="postInfo desktop" id="pi147947205"><input type="checkbox" name="147947205" value="delete"> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span class="dateTime" data-utc="1468092935">07/09/16(Sat)21:35:35</span> <span class="postNum desktop"><a href="#p147947205" title="Link to this post">No.</a><a href="javascript:quote('147947205');" title="Reply to this post">147947205</a></span><a class="menu-button" href="javascript:;"><i class="fa fa-angle-down"></i></a><span class="container"></span></div><div class="file" id="f147947205"><div class="fileText" id="fT147947205"><span class="file-info"><a href="http://i.4cdn.org/vg/1468092935927.jpg" target="_blank">gevyimlax4s6zigqbwv0[1].jpg</a> (251 KB, 757x720)</span><span class="fileText-original">File: <a href="//i.4cdn.org/vg/1468092935927.jpg" target="_blank">gevyimlax4s6zigqbwv0[1].jpg</a> (251 KB, 757x720)</span> <a target="_blank" class="sauce" href="https://www.google.com/searchbyimage?image_url=http%3A%2F%2Fi.4cdn.org%2Fvg%2F1468092935927.jpg&amp;safe=off">google</a> <a target="_blank" class="sauce"></a> <a target="_blank" class="sauce" href="//iqdb.org/?url=http%3A%2F%2Fi.4cdn.org%2Fvg%2F1468092935927.jpg">iqdb</a> <a target="_blank" class="sauce" href="https://whatanime.ga/?auto&amp;url=http%3A%2F%2Fi.4cdn.org%2Fvg%2F1468092935927.jpg">wait</a> <a target="_blank" class="sauce"></a> <a target="_blank" class="sauce"></a> <a target="_blank" class="sauce"></a></div><a class="fileThumb" href="//i.4cdn.org/vg/1468092935927.jpg" target="_blank"><img src="//i.4cdn.org/vg/1468092935927s.jpg" alt="251 KB" data-md5="4G85etlVSm/VGb78w3mHtg==" style="height: 118px; width: 125px;"><div data-tip="" data-tip-cb="mShowFull" class="mFileInfo mobile">251 KB JPG</div></a></div><blockquote class="postMessage" id="m147947205"><a href="#p147947031" class="quotelink">&gt;&gt;147947031</a></blockquote></div></div>`

**Comment by ccd0** [comment]
You appear to have multiple copies of 4chan X enabled at once. Disabling or uninstalling all but one will fix the problem.
