### ISSUE TITLE
4chan X Chrome extension unable to save data after update until page refreshed

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1012]
Due to issues with chrome.storage:
https://bugs.chromium.org/p/chromium/issues/detail?id=626952

Working on a potential workaround.

**Comment by ccd0** [comment]
This now causes an error instead of failing silently (#1084):

[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.12.2.1 crx
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
URL: http://boards.4chan.org/qst/thread/580356#p581163

Error: Invocation of form get(, function) doesn't match definition get(optional string or array or object keys, function callback)
at normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at StorageArea.self.(anonymous function) [as get] (extensions::StorageArea:35:14)
    at get (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4358:35)
    at Function.$.get (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4373:5)
    at Object.dialog (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:10649:7)
    at Object.dialog (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:19926:25)
    at Object.open (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:19505:14)
    at Object.openPost (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:19662:10)
    at HTMLAnchorElement.quote (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:19730:10)

**Comment by ccd0** [comment]
#1126, #1127
