### ISSUE TITLE
"WEBM Metadata" crashed on node Post No.353725617 (v).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1133]
Submitter: aaron
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.13.0.4 userscript
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
URL: http://boards.4chan.org/v/thread/353724404

TypeError: el is null
Metadata</Metadata.node@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X-noupdate.user.js:13140:1
Callbacks</Callbacks.prototype.execute@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X-noupdate.user.js:5040:13
Main</Main.callbackNodes@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X-noupdate.user.js:23351:9
Fetcher</Fetcher.prototype.insert@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X-noupdate.user.js:5413:7
Fetcher@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X-noupdate.user.js:5392:9
QuotePreview</QuotePreview.mouseover@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X-noupdate.user.js:22376:7

`<div data-clone="0" data-full-i-d="v.353725617" class="postContainer replyContainer hasInline" id="19pc353725617"><div id="19sa353725617"><a href="javascript:;" class="hide-reply-button"><span class="fa fa-minus-square-o"></span></a></div><div id="19p353725617" class="post reply"><div class="postInfoM mobile" id="19pim353725617"><span class="nameBlock"><span class="name">Anonymous</span><br></span><span class="dateTime postNum" data-utc="1475563169">10/04/16(Tue)02:39:29 <a href="#p353725617" title="Link to this post">No.</a><a href="javascript:quote('353725617');" title="Reply to this post">353725617</a></span></div><div class="postInfo desktop" id="19pi353725617"><input name="353725617" value="delete" type="checkbox"> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span class="dateTime" data-utc="1475563169">04/10/16(Tue)07:39:29</span> <span class="postNum desktop"><a href="#p353725617" title="Link to this post">No.</a><a href="javascript:quote('353725617');" title="Reply to this post">353725617</a></span><a href="javascript:;" class="menu-button"><i class="fa fa-angle-down"></i></a><span class="container"><a class="backlink" href="#p353725663">&gt;&gt;353725663</a> <a class="backlink" href="#p353725937">&gt;&gt;353725937</a> <a class="backlink" href="#p353730362">&gt;&gt;353730362</a> <a class="backlink" href="#p353734796">&gt;&gt;353734796</a> <a class="backlink" href="#p353736448">&gt;&gt;353736448</a></span></div><div class="file" id="19f353725617"><div class="fileText" id="19fT353725617"><span class="file-info"><a href="http://i.4cdn.org/v/1475563169946.webm" target="_blank">FFXVdeathmagic.webm</a> <a href="http://i.4cdn.org/v/1475563169946.webm" download="FFXVdeathmagic.webm" class="fa fa-download download-button"></a> (3 MB, 960x540)</span><span class="fileText-original">File: <a href="//i.4cdn.org/v/1475563169946.webm" target="_blank">FFXVdeathmagic.webm</a> (3 MB, 960x540)</span> <a href="//iqdb.org/?url=http%3A%2F%2Fi.4cdn.org%2Fv%2F1475563169946s.jpg" class="sauce" target="_blank">iqdb</a> <a href="http://www.google.com/searchbyimage?image_url=http%3A%2F%2Fi.4cdn.org%2Fv%2F1475563169946s.jpg" class="sauce" target="_blank">google</a> <a class="sauce" target="_blank"></a> <a class="sauce" target="_blank"></a> <a href="https://whatanime.ga/?auto&amp;url=http%3A%2F%2Fi.4cdn.org%2Fv%2F1475563169946s.jpg" class="sauce" target="_blank">wait</a> <span tabindex="0" class="webm-title not-found"><span></span><a tabindex="-1" href="javascript:;"></a></span></div><a class="fileThumb" href="//i.4cdn.org/v/1475563169946.webm" target="_blank"><img src="//i.4cdn.org/v/1475563169946s.jpg" alt="3 MB" data-md5="mZeS7B/CfvPc9pUGFRwsew==" style="height: 70px; width: 125px;"><div data-tip="" data-tip-cb="mShowFull" class="mFileInfo mobile">3 MB WEBM</div></a></div><blockquote class="postMessage" id="19m353725617"><a href="#p353725340" class="quotelink">&gt;&gt;353725340</a><br>The fuck are you talking about? The game is complete already and it's already the best looking open world Action RPG ever made. You are just some meme spouting faggot that knows fuck all about anything so go kill yourself.<br><br><a href="#p353725425" class="quotelink">&gt;&gt;353725425</a><br>Latest build doesn't, all you've seen is months old outdated builds. Even Witcher 3 had a fuckton of bugs and glitches on release.<br><br>Anyone who thinks it's getting delayed again is a goddamn fucking retard.</blockquote></div></div>`

**Comment by ccd0** [comment]
#1147

Submitter: anonib
I just opened a webm.

Script: 4chan X ccd0 v1.13.0.7 crx
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
URL: http://boards.4chan.org/sp/thread/71842324

TypeError: Cannot read property 'children' of null
at _Class.node (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:13096:13)
    at Callbacks.execute (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:4963:17)
    at Object.callbackNodes (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:23307:12)
    at Fetcher.insert (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:5336:12)
    at new Fetcher (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:5315:14)
    at HTMLAnchorElement.mouseover (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:22332:7)

`<div class="postContainer replyContainer hasInline" id="23pc71842553" data-full-i-d="sp.71842553" data-clone="0"><div id="23sa71842553"><a class="hide-reply-button" href="javascript:;"><span class="fa fa-minus-square-o"></span></a></div><div id="23p71842553" class="post reply"><div class="postInfoM mobile" id="23pim71842553"><span class="nameBlock"><span class="name">Anonymous</span> <span title="United States" class="flag flag-us"></span><br></span><span class="dateTime postNum" data-utc="1476235834">10/11/16(Tue)21:30:34 <a href="#p71842553" title="Link to this post">No.</a><a href="javascript:quote('71842553');" title="Reply to this post">71842553</a></span></div><div class="postInfo desktop" id="23pi71842553"><input type="checkbox" name="71842553" value="delete"> <span class="nameBlock"><span class="name">Anonymous</span> <span title="United States" class="flag flag-us"></span></span> <span class="dateTime" data-utc="1476235834">10/11/16(Tue)20:30:34</span> <span class="postNum desktop"><a href="#p71842553" title="Link to this post">No.</a><a href="javascript:quote('71842553');" title="Reply to this post">71842553</a></span><a class="menu-button" href="javascript:;"><i class="fa fa-angle-down"></i></a><span class="container"><a href="#p71842629" class="backlink">&gt;&gt;71842629</a> <a href="#p71842635" class="backlink">&gt;&gt;71842635</a> <a href="#p71842765" class="backlink">&gt;&gt;71842765</a></span></div><div class="file" id="23f71842553"><div class="fileText" id="23fT71842553"><span class="file-info"><a href="http://i.4cdn.org/sp/1476235834444.webm" target="_blank">[1280x720] Paige VanZant (@PaigeVanzantUFC) Twitter.webm</a> (1.57 MB, <a href="http://i.4cdn.org/sp/1476235834444.webm" download="[1280x720] Paige VanZant (@PaigeVanzantUFC) Twitter.webm" class="fa fa-download download-button"></a> 1000x563)</span><span class="fileText-original">File: <a title="[1280x720] Paige VanZant (@PaigeVanzantUFC) Twitter.webm" href="//i.4cdn.org/sp/1476235834444.webm" target="_blank">[1280x720] Paige VanZant (...).webm</a> (1.57 MB, 1000x563)</span> <a target="_blank" class="sauce" href="https://www.google.com/searchbyimage?image_url=http%3A%2F%2Fi.4cdn.org%2Fsp%2F1476235834444s.jpg&amp;safe=off">google</a> <a target="_blank" class="sauce"></a> <a target="_blank" class="sauce" href="//iqdb.org/?url=http%3A%2F%2Fi.4cdn.org%2Fsp%2F1476235834444s.jpg">iqdb</a> <a target="_blank" class="sauce" href="https://whatanime.ga/?auto&amp;url=http%3A%2F%2Fi.4cdn.org%2Fsp%2F1476235834444s.jpg">wait</a> <a target="_blank" class="sauce"></a> <a target="_blank" class="sauce"></a> <a target="_blank" class="sauce"></a> <span class="webm-title"><a href="javascript:;"></a></span></div><a class="fileThumb" href="http://i.4cdn.org/sp/1476235834444.webm" target="_blank"><img src="//i.4cdn.org/sp/1476235834444s.jpg" alt="1.57 MB" data-md5="lYYroZrgWXWlamh5/Omd4w==" style="height: 70px; width: 125px;" class=""><div data-tip="" data-tip-cb="mShowFull" class="mFileInfo mobile">1.57 MB WEBM</div></a></div><blockquote class="postMessage" id="23m71842553"><span class="quote">&gt;tfw Paige will never punch you in the butt</span></blockquote></div></div>`

**Comment by ccd0** [comment]
#1151
Submitter: wewlad
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.13.0.12 crx
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2501.0 Safari/537.36
URL: https://boards.4chan.org/o/thread/15993929

TypeError: Cannot read property 'children' of null
at _Class.Metadata.node (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:13120:13)
    at Callbacks.execute (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:4974:17)
    at Object.Main.callbackNodes (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:23360:12)
    at Fetcher.insert (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:5347:12)
    at new Fetcher (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:5326:14)
    at HTMLAnchorElement.QuotePreview.mouseover (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:22385:7)

`<div class="postContainer replyContainer hasInline" id="76pc15994011" data-full-i-d="o.15994011" data-clone="0"><div id="76sa15994011"><a class="hide-reply-button" href="javascript:;"><span class="fa fa-minus-square-o"></span></a></div><div id="76p15994011" class="post reply"><div class="postInfoM mobile" id="76pim15994011"><span class="nameBlock"><span class="name">Anonymous</span><br></span><span class="dateTime postNum" data-utc="1476395006">10/13/16(Thu)17:43:26 <a href="#p15994011" title="Link to this post">No.</a><a href="javascript:quote('15994011');" title="Reply to this post">15994011</a></span></div><div class="postInfo desktop" id="76pi15994011"><input type="checkbox" name="15994011" value="delete"> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span class="dateTime" data-utc="1476395006" title="10/13/16(Thu)17:43:26">17 hours ago</span> <span class="postNum desktop"><a href="#p15994011" title="Link to this post">No.</a><a href="javascript:quote('15994011');" title="Reply to this post">15994011</a></span><a class="menu-button" href="javascript:;"><i class="fa fa-angle-down"></i></a><span class="container"><a href="#p15995725" class="backlink">&gt;&gt;15995725</a> <a href="#p15995951" class="backlink">&gt;&gt;15995951</a> <a href="#p15996440" class="backlink">&gt;&gt;15996440</a></span></div><div class="file" id="76f15994011"><div class="fileText" id="76fT15994011"><span class="file-info"><a href="https://i.4cdn.org/o/1476395006750.webm" target="_blank">1475346216463.webm</a> (2.38 MB, 640x640)</span><span class="fileText-original">File: <a href="https://i.4cdn.org/o/1476395006750.webm" target="_blank">1475346216463.webm</a> (2.38 MB, 640x640)</span> <a target="_blank" class="sauce" href="https://www.google.com/searchbyimage?image_url=https%3A%2F%2Fi.4cdn.org%2Fo%2F1476395006750s.jpg&amp;safe=off">google</a> <a target="_blank" class="sauce"></a> <a target="_blank" class="sauce"></a> <a target="_blank" class="sauce" href="https://whatanime.ga/?auto&amp;url=https%3A%2F%2Fi.4cdn.org%2Fo%2F1476395006750s.jpg">wait</a> <span class="webm-title"><a href="javascript:;"></a></span></div><a class="fileThumb" href="https://i.4cdn.org/o/1476395006750.webm" target="_blank"><img src="//i.4cdn.org/o/1476395006750s.jpg" alt="2.38 MB" data-md5="1nu2vDRoApJLrZKO10PYDg==" style="height: 125px; width: 125px;"><div data-tip="" data-tip-cb="mShowFull" class="mFileInfo mobile">2.38 MB WEBM</div></a></div><blockquote class="postMessage" id="76m15994011"></blockquote></div></div>`

**Comment by ccd0** [comment]
#1163
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.13.0.14 userscript
User agent: Mozilla/5.0 (X11; Linux i686; rv:38.9) Gecko/20100101 Goanna/2.2 Firefox/38.9 PaleMoon/26.5.0
URL: http://boards.4chan.org/a/thread/148873176

TypeError: el is null
Metadata</Metadata.node@4chan-X-beta.user.js:13211
Callbacks</Callbacks</Callbacks.prototype.execute@4chan-X-beta.user.js:5062
Main</Main.callbackNodes@4chan-X-beta.user.js:23452
Fetcher</Fetcher</Fetcher.prototype.insert@4chan-X-beta.user.js:5435
Fetcher@4chan-X-beta.user.js:5414
QuotePreview</QuotePreview.mouseover@4chan-X-beta.user.js:22476

`<div data-clone="0" data-full-i-d="a.148929990" id="63pc148929990" class="postContainer replyContainer xl-post-linkified hasInline"><div class="sideArrows" id="63sa148929990">&gt;&gt;</div><div id="63p148929990" class="post reply"><div class="postInfo desktop" id="63pi148929990"><input name="148929990" value="delete" type="checkbox"> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span title="10/24/16(Mon)06:46:56" class="dateTime" data-utc="1477266416">1 hour ago</span> <span class="postNum desktop"><a href="#p148929990" title="Link to this post">No.</a><a href="javascript:quote('148929990');" title="Reply to this post">148929990</a></span><a href="javascript:;" class="menu-button"><i class="fa fa-angle-down"></i></a><span class="container"><a class="backlink" href="#p148930219">&gt;&gt;148930219</a> <a class="backlink" href="#p148931586">&gt;&gt;148931586</a> <a class="backlink" href="#p148931706">&gt;&gt;148931706</a> <a class="backlink" href="#p148932807">&gt;&gt;148932807</a></span></div><div class="file" id="63f148929990"><div class="fileText" id="63fT148929990"><span class="file-info"><a href="http://i.4cdn.org/a/1477266416567.webm" target="_blank">1465122921063.webm</a> (237 KB, 300x370)</span><span class="fileText-original">File: <a href="//i.4cdn.org/a/1477266416567.webm" target="_blank">1465122921063.webm</a> (237 KB, 300x370)</span> <a href="https://www.google.com/searchbyimage?image_url=http%3A%2F%2Fi.4cdn.org%2Fa%2F1477266416567s.jpg&amp;safe=off" class="sauce" target="_blank">google</a> <a href="//iqdb.org/?url=http%3A%2F%2Fi.4cdn.org%2Fa%2F1477266416567s.jpg" class="sauce" target="_blank">iqdb</a> <a href="//saucenao.com/search.php?url=http%3A%2F%2Fi.4cdn.org%2Fa%2F1477266416567s.jpg" class="sauce" target="_blank">saucenao</a> <a class="sauce" target="_blank"></a> <a class="sauce" target="_blank"></a> <a href="https://whatanime.ga/?auto&amp;url=http%3A%2F%2Fi.4cdn.org%2Fa%2F1477266416567s.jpg" class="sauce" target="_blank">wait</a> <span class="webm-title"><a href="javascript:;"></a></span></div><a class="fileThumb" href="//i.4cdn.org/a/1477266416567.webm" target="_blank"><img src="//i.4cdn.org/a/1477266416567s.jpg" alt="237 KB" data-md5="ketO6jBEl5zVyQP71NPayw==" style="height: 125px; width: 101px;"></a></div><blockquote class="postMessage" id="63m148929990"><a data-xl-link-events="gallery_tag" data-xl-href="https://exhentai.org/g/989370/472793d882/" data-xl-site="ehentai" class="xl-site-tag xl-theme xl-theme-dark xl-link-events" rel="noreferrer" target="_blank"><span data-xl-site-tag-icon="exhentai" class="xl-site-tag-icon xl-theme xl-theme-dark"></span><span class="xl-site-tag-text">[Ex]</span></a><a data-xl-link-events="gallery_link" data-xl-id="ehentai_989370" href="https://exhentai.org/g/989370/472793d882/" target="_blank" rel="noreferrer" class="linkify xl-link xl-linkified xl-link-events xl-link-formatted"><span class="xl-link-inner">[Double Deck Seisakujo (Double Deck)] PHASE4 : Dai 4-shu Sekkin Souguu [Digital]</span></a><br>who /x/ here?</blockquote></div></div>`

**Comment by ccd0** [comment]
Probably a conflict with another extension, but not clear what. Probably not ExLinks.

**Comment by ccd0** [comment]
Actually, another extension shouldn't do this since this is happening before the post is inserted. Odd.

**Comment by ccd0** [comment]
Have managed to reproduce. This is on 4chan X's end.

**Comment by ccd0** [comment]
Reproduction steps: Find post with webm (A), linked to by post with non-webm file (B). Starting from A, inline a backlink to B, then hover preview the link to A.

**Comment by ccd0** [comment]
Bug is related to cloning rather than webms, that just happens to be the only code that triggers it.
