### ISSUE TITLE
"Menu" crashed on node Post No.163363902 (vg).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1235]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.13.2.3 crx
User agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2866.0 Safari/537.36
URL: https://boards.4chan.org/vg/thread/163202704

TypeError: Cannot read property 'classList' of null
at Function.$.rmClass (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4535:9)
    at _Class.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:15124:11)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5184:17)
    at Object.callbackNodes (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:23882:12)
    at Fetcher.insert (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5557:12)
    at new Fetcher (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5536:14)
    at HTMLAnchorElement.mouseover (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22896:7)

`<div class="postContainer replyContainer" id="1pc163363902" data-full-i-d="vg.163363902" data-clone="0"><div class="sideArrows" id="1sa163363902">&gt;&gt;</div><div id="1p163363902" class="post reply"><div class="postInfoM mobile" id="1pim163363902"><span class="nameBlock"><span class="name">Anonymous</span><br></span><span class="dateTime postNum" data-utc="1482346466">12/21/16(Wed)13:54:26 <a href="#p163363902" title="Link to this post">No.</a><a href="javascript:quote('163363902');" title="Reply to this post">163363902</a></span></div><div class="postInfo desktop" id="1pi163363902"><input type="checkbox" name="163363902" value="delete"> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span class="dateTime" data-utc="1482346466">12/21/16(Wed)13:54:26</span> <span class="postNum desktop"><a href="#p163363902" title="Link to this post">No.</a><a href="javascript:quote('163363902');" title="Reply to this post">163363902</a></span></div><div class="file" id="1f163363902"><div class="fileText" id="1fT163363902">File: <a href="//is.4chan.org/vg/1482346466641.jpg" target="_blank">1482344391587.jpg</a> (350 KB, 1944x1210)</div><a class="fileThumb" href="https://is.4chan.org/vg/1482346466641.jpg" target="_blank"><img src="//i.4cdn.org/vg/1482346466641s.jpg" alt="350 KB" data-md5="0bLGLhH50WoZm49Ffk7U1A==" style="height: 77px; width: 125px;"><div data-tip="" data-tip-cb="mShowFull" class="mFileInfo mobile">350 KB JPG</div></a></div><blockquote class="postMessage" id="1m163363902"></blockquote></div></div>`

**Comment by ccd0** [comment]
#1250

Submitter: ralph
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.13.3.0 crx
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
URL: http://boards.4chan.org/pol/thread/106528317

TypeError: Cannot read property 'classList' of null
at Function.$.rmClass (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4535:9)
    at _Class.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:15156:11)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5185:17)
    at Object.callbackNodes (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:23917:12)
    at Fetcher.insert (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5558:12)
    at new Fetcher (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5537:14)
    at HTMLAnchorElement.mouseover (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22928:7)

`<div class="postContainer replyContainer" id="0pc106547925" data-full-i-d="pol.106547925" data-clone="0"><div class="sideArrows" id="0sa106547925">&gt;&gt;</div><div id="0p106547925" class="post reply"><div class="postInfoM mobile" id="0pim106547925"><span class="nameBlock"><span class="name">Anonymous</span> <span class="posteruid id_/UcfcWF5">(ID: <span class="hand" title="Highlight posts by this ID">/UcfcWF5</span>)</span> <span title="United States" class="flag flag-us"></span><br></span><span class="dateTime postNum" data-utc="1484104754">01/10/17(Tue)22:19:14 <a href="#p106547925" title="Link to this post">No.</a><a href="javascript:quote('106547925');" title="Reply to this post">106547925</a></span></div><div class="postInfo desktop" id="0pi106547925"><input type="checkbox" name="106547925" value="delete"> <span class="nameBlock"><span class="name">Anonymous</span>  <span class="posteruid id_/UcfcWF5">(ID: <span class="hand" title="Highlight posts by this ID">/UcfcWF5</span>)</span> <span title="United States" class="flag flag-us"></span></span> <span class="dateTime" data-utc="1484104754">01/10/17(Tue)22:19:14</span> <span class="postNum desktop"><a href="#p106547925" title="Link to this post">No.</a><a href="javascript:quote('106547925');" title="Reply to this post">106547925</a></span></div><blockquote class="postMessage" id="0m106547925"><a href="#p106547749" class="quotelink">&gt;&gt;106547749</a><br><span class="quote">&gt;working for walmart</span></blockquote></div></div>`

**Comment by ccd0** [comment]
Bug confirmed. Happens when a post clone is created for quote previewing / hovering before callbacks have been run on the original.
