### ISSUE TITLE
"Reply Hiding" crashed on node Post No.60368697 (g).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1364]
Submitter: huhu
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.13.8.7 crx
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36
URL: http://boards.4chan.org/g/thread/60368673

TypeError: Cannot read property 'firstChild' of null
at Post.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:7485:27)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5253:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:24172:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:24176:16)
    at Object.callbackNodesDB (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:24187:14)
    at Object.initThread (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:24141:21)
    at initReady (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:24085:21)
    at HTMLDocument.cb (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4360:14)

`<div class="postContainer replyContainer noFile" id="pc60368697" data-full-i-d="g.60368697"><div id="sa60368697"><a class="hide-reply-button" href="javascript:;"><span class="fa fa-minus-square-o"></span></a></div><div id="p60368697" class="post reply"><div class="postInfoM mobile" id="pim60368697"><span class="nameBlock"><span class="name">SpeedShit</span><br></span><span class="dateTime postNum" data-utc="1494686542">05/13/17(Sat)10:42:22 <a href="#p60368697" title="Link to this post">No.</a><a href="javascript:quote('60368697');" title="Reply to this post">60368697</a></span></div><div class="postInfo desktop" id="pi60368697"><input type="checkbox" name="60368697" value="delete"> <span class="nameBlock"><span class="name">SpeedShit</span> </span> <span class="dateTime" data-utc="1494686542">05/13/17(Sat)10:42:22</span> <span class="postNum desktop"><a href="#p60368697" title="Link to this post">No.</a><a href="javascript:quote('60368697');" title="Reply to this post">60368697</a></span><a class="menu-button" href="javascript:;"><i class="fa fa-angle-down"></i></a><span class="container"></span></div><blockquote class="postMessage" id="m60368697"><a href="#p60368673" class="quotelink">&gt;&gt;60368673<span class="qmark-op">&nbsp;(OP)</span></a><br><br>I'm from Venezuela</blockquote></div></div>`

**Comment by ccd0** [comment]
Looks like you're running multiple copies of 4chan X. Check that, and if you're still having problems, please open another bug report.
