### ISSUE TITLE
"Quote Inlining" crashed on node Post No.9354586 (trash).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1373]
Submitter: plz send halp
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.13.8.7 crx
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
URL: https://boards.4chan.org/trash/thread/9345340

TypeError: Cannot read property 'insertBefore' of null
at Function.$.after (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4649:27)
    at process (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22903:13)
    at Post.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22897:9)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5253:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:24172:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:24176:16)

`<div class="postContainer replyContainer" id="pc9354586" data-full-i-d="trash.9354586"><div id="sa9354586"><a class="hide-reply-button" href="javascript:;"><span class="fa fa-minus-square-o"></span></a></div><div id="p9354586" class="post reply"><div class="postInfoM mobile" id="pim9354586"><span class="nameBlock"><span class="name">Anonymous</span><br></span><span class="dateTime postNum" data-utc="1494903677">05/15/17(Mon)23:01:17 <a href="#p9354586" title="Link to this post">No.</a><a href="javascript:quote('9354586');" title="Reply to this post">9354586</a></span></div><div class="postInfo desktop" id="pi9354586"><input type="checkbox" name="9354586" value="delete"> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span class="dateTime" data-utc="1494903677">05/15/17(Mon)23:01:17</span> <span class="postNum desktop"><a href="#p9354586" title="Link to this post">No.</a><a href="javascript:quote('9354586');" title="Reply to this post">9354586</a></span><a href="#" class="postMenuBtn" title="Post menu" data-cmd="post-menu">▶</a><div id="bl_9354586" class="backlink"><span><a href="#p9354733" class="quotelink">&gt;&gt;9354733</a> </span><span><a href="#p9354872" class="quotelink">&gt;&gt;9354872</a> </span><span><a href="#p9354883" class="quotelink">&gt;&gt;9354883</a> </span><span><a href="#p9355231" class="quotelink">&gt;&gt;9355231</a> </span></div><a class="menu-button" href="javascript:;"><i class="fa fa-angle-down"></i></a></div><div class="file" id="f9354586"><div class="fileText" id="fT9354586">File: <a title="She isn't in Heatherween III though.jpg" href="//i.4cdn.org/trash/1494903677058.jpg" target="_blank">She isn't in Heatherween (...).jpg</a> (46 KB, 640x564)</div><a class="fileThumb" href="//i.4cdn.org/trash/1494903677058.jpg" target="_blank"><img src="//i.4cdn.org/trash/1494903677058s.jpg" alt="46 KB" data-md5="CATpO6pgiKA/kkLnM7uwAQ==" style="height: 110px; width: 125px;"><div data-tip="" data-tip-cb="mShowFull" class="mFileInfo mobile">46 KB JPG</div></a></div><blockquote class="postMessage" id="m9354586"><a href="#p9353668" class="quotelink">&gt;&gt;9353668</a><br>Michael Myers. Heather Hoss. Works pretty well. The amount of rubber horse masks doesn't hurt either.</blockquote></div></div>`

**Comment by ccd0** [comment]
Merged to #1372.
Please let me know what other extensions you're using, and if this goes away if you turn them off.
