### ISSUE TITLE
"Linkify" crashed on node Post No.62477139 (fit).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#3126]
Submitter: Walter Luigi
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.14.21.5 crx
URL: https://boards.4channel.org/fit/
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

Error: Extension context invalidated.
at chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5652:29
    at ajax (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5748:7)
    at Function.$.cache (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5032:29)
    at Object.cache (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5763:16)
    at Object.title (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:16583:28)
    at Object.process (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:16485:21)
    at Post.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17260:19)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5873:17)
    at Object.callbackNodes (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:28060:12)
    at Object.buildThreads (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:12138:12)

`<div class="postContainer opContainer" id="pc62477139" data-full-i-d="fit.62477139"><div id="p62477139" class="post op"><div class="file" id="f62477139"><div class="fileText" id="fT62477139">File: <a href="https://i.4cdn.org/fit/1625717579037.jpg" target="_blank">SwimsuitGifau3.jpg</a> (139 KB, 960x798)</div><a class="fileThumb" href="https://i.4cdn.org/fit/1625717579037.jpg" target="_blank"><img src="//i.4cdn.org/fit/1625717579037s.jpg" alt="139 KB" data-md5="zz6IbU7JMso6gP0+aA7RTQ==" style="height: 207px; width: 250px;" loading="lazy"></a></div><div class="postInfo desktop" id="pi62477139"><input type="checkbox" name="62477139" value="delete"> <span class="subject">Uh... Guys? The home gym is possible</span> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span class="dateTime" data-utc="1625717579">07/08/21(Thu)00:12:59</span> <span class="postNum desktop"><a href="/fit/thread/62477139#p62477139" title="Link to this post">No.</a><a href="/fit/thread/62477139#q62477139" title="Reply to this post">62477139</a> <span class="page-num" title="This thread is on page 2 in the original index.">[2]</span> <span>[<a href="/fit/thread/62477139" class="replylink">Reply</a>]</span></span></div><blockquote class="postMessage" id="m62477139"><span class="quote">&gt;0 = 3 sets of 3 pushups</span><br><span class="quote">&gt;1 = 3 sets of 3 curls</span><br><span class="quote">&gt;2 = 3 sets of 10 military press</span><br><span class="quote">&gt;3 = 3 sets of 10 pushups</span><br><span class="quote">&gt;4 = 3 sets of 12 second 1 inch leg lifts</span><br><span class="quote">&gt;5 = 3 sets of 20 pushups</span><br><span class="quote">&gt;6 = Drink a glass of water</span><br><span class="quote">&gt;7 = Lose 10 pounds in the next month &amp; we'll fly you to Houton for sirgery</span><br><span class="quote">&gt;8 = 3 sets of 3 military press</span><br><span class="quote">&gt;9 = Have a pepsi knock off by La Croix &amp; take a break</span><br><br>WTF?! You DON'T need a home pull down machine to do a pull up?! WTF?!<br><br><a class="linkify youtube" rel="noreferrer noopener" target="_blank" href="https://youtu.be/fO3dKSQayfg">https://youtu.be/fO3dKSQayfg</a> <a class="embedder" href="javascript:;" data-key="YouTube" data-uid="fO3dKSQayfg" data-options="" data-href="https://youtu.be/fO3dKSQayfg">(<span>un</span>embed)</a></blockquote></div></div>`

**Comment by saxamaphone69** [comment]
Keeping this issue open to address reported `Linkify` crashes. Of course, this hasn't occured since gitreports died, and from what it looks like, a lot of these links still linkified?

While https://github.com/ccd0/4chan-x/commit/84b52e2a40644cf3c80b7312ea282dc0f4799e78 fixed the original issue with `gmReq`, these appear to be something different.

Seems to occur on both the userscript and extension, Firefox and Chrome.

| Issue | Potential Linkify issue |
| ----- | ----------------------- |
| #1424 | `ftp:passive-mode` |
| #1434 | Error message failed |
| #1470 | `irc:rejoin` |
| #1483 | `127.0.0.1:6881;`, `http://0.0.0.0/0;`, `http://chihaya/;` |
| #1570 | `http://main.rs:14:13` |
| #2236 | `https://www.f@ceb00k.com/DonaldTrump/photos/a.488852220724/10162241664440725` |

say:

```
Error: Invalid argument.
at ImageHost.fixLinks (Function code:13364:9)
at Linkify.node (Function code:14923:9)
at Callbacks.prototype.execute (Function code:5360:13)
at Main.callbackNodes (Function code:24606:9)
at Index.buildReplies (Function code:10333:7)
at Index.buildStructure (Function code:10516:9)
at Index.buildIndex (Function code:10503:9)
at Index.pageLoad (Function code:9984:9)
at Index.parse (Function code:10185:7)
at Index.load (Function code:10150:11)
```

It stopped for ~2 years, then in 2019 instead of `Error: Invalid argument.` said `Error: A security problem occurred.`.

| Issue | Potential Linkify issue |
| ----- | ----------------------- |
| #2329 | soundcloud |
| #2357 | youtube |
| #2365 | nothing provided | 
| #2373 | streamable |
| #2379 | nothing provided |
| #2384 | mega and streamable |

```
Error: Exposing privileged or cross-origin callable is prohibited
ajax@4chan%20X.user.js:5575:20
$</$.cache@4chan%20X.user.js:4745:14
cache@4chan%20X.user.js:5585:14
title@4chan%20X.user.js:15560:16
process@4chan%20X.user.js:15460:11
node@4chan%20X.user.js:16182:9
Callbacks</Callbacks.prototype.execute@4chan%20X.user.js:5679:13
fn@4chan%20X.user.js:26113:9
softTask@4chan%20X.user.js:26117:16
```

or

```
Error: Exposing privileged or cross-origin callable is prohibited
ajax@4chan-X.user.js:5634:20
$</$.cache@4chan-X.user.js:4774:14
cache@4chan-X.user.js:5644:14
title@4chan-X.user.js:15624:16
process@4chan-X.user.js:15524:11
node@4chan-X.user.js:16288:9
Callbacks</Callbacks.prototype.execute@4chan-X.user.js:5738:13
callbackNodes@4chan-X.user.js:26278:9
buildThreads@4chan-X.user.js:11419:7
buildCatalogPart@4chan-X.user.js:11702:17
fn@4chan-X.user.js:11687:17
execTask@4chan-X.user.js:5073:14
```

(funnily, #2951 brings this back, albeit updated lines)

```
Error: Exposing privileged or cross-origin callable is prohibited
ajax@4chan-X.user.js:5909:20
$</$.cache@4chan-X.user.js:5000:14
cache@4chan-X.user.js:5919:14
title@4chan-X.user.js:16704:16
process@4chan-X.user.js:16606:11
node@4chan-X.user.js:17381:9
Callbacks</Callbacks.prototype.execute@4chan-X.user.js:6020:13
callbackNodes@4chan-X.user.js:28033:9
buildThreads@4chan-X.user.js:12287:7
buildCatalogPart@4chan-X.user.js:12570:17
fn@4chan-X.user.js:12555:17
execTask@4chan-X.user.js:5305:14
```

And then the error changed in #2393 and says:

```
Error: Extension context invalidated.
at chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:5601:29
at ajax (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:5697:7)
at Function.$.cache (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:4987:29)
at Object.cache (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:5712:16)
at Object.title (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:16418:28)
at Object.process (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:16318:21)
at Post.node (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:17085:19)
at Callbacks.execute (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:5822:17)
at fn (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:27677:13)
at softTask (chrome-extension://lacclbnghgdicfifcamcmcnilckjamag/script.js:27681:16)
```

And randomly, #2541 (perhaps OneeChan conflict) and #2558 (failed to linkify some of the links):

```
Error
String.fromCharCode@https://boards.4chan.org/pol/ line 5139 > scriptElement:8:21
makeLink/text<@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:17468:27
makeLink@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:17464:33
process@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:17419:28
node@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:17358:23
Callbacks</Callbacks</Callbacks.prototype.execute@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:5996:17
callbackNodes@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:27987:12
buildThreads@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:12228:12
buildCatalogPart@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:12504:23
fn@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:12489:23
buildCatalog@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:12500:7
buildIndex@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:12453:15
pageLoad@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:11906:15
parse@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:12099:20
load@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:12064:17
onloadend@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/4chan%20X.user.js#1:4934:19
m/y</</</o[e]@https://boards.4chan.org/pol/:1:11767
Theme@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/OneeChan.user.js#2:4236:26
init@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/OneeChan.user.js#2:3045:29
init@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/OneeChan.user.js#2:1008:24
@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/OneeChan.user.js#2:4375:9
@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/OneeChan.user.js#2:4376:3
@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/OneeChan.user.js#2:4378:3
@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/OneeChan.user.js#2:4378:7
value@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/OneeChan.user.js#2:1:142
y/</<@https://boards.4chan.org/pol/:1:20071
y/<@https://boards.4chan.org/pol/:1:20083
value@https://boards.4chan.org/pol/:1:10087
@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/OneeChan.user.js#2:1:74
@moz-extension://3a77fe1e-8797-4ef6-915e-434022117b17/OneeChan.user.js#2:1:79
l/<@https://boards.4chan.org/pol/:1:9988
l@https://boards.4chan.org/pol/:1:9999
h@https://boards.4chan.org/pol/:1:20153
LoadScripts@https://boards.4chan.org/pol/:1:20467
onHandle@https://boards.4chan.org/pol/:1:3392
c/<@https://boards.4chan.org/pol/:1:9890
```

```
TypeError: fromCharCode0 is undefined
String.fromCharCode@https://boards.4chan.org/h/ line 5141 > scriptElement:10:13
makeLink/text<@moz-extension://3780181e-a070-4655-8b7f-22c497de2afc/userscripts/4chan%20X.user.js?id=98594ecb-4dc5-4f06-bcf9-b7154d0c51f1:17476:27
makeLink@moz-extension://3780181e-a070-4655-8b7f-22c497de2afc/userscripts/4chan%20X.user.js?id=98594ecb-4dc5-4f06-bcf9-b7154d0c51f1:17472:33
process@moz-extension://3780181e-a070-4655-8b7f-22c497de2afc/userscripts/4chan%20X.user.js?id=98594ecb-4dc5-4f06-bcf9-b7154d0c51f1:17427:28
node@moz-extension://3780181e-a070-4655-8b7f-22c497de2afc/userscripts/4chan%20X.user.js?id=98594ecb-4dc5-4f06-bcf9-b7154d0c51f1:17366:23
tms_98594ecb_4dc5_4f06_bcf9_b7154d0c51f1/</Callbacks</Callbacks</Callbacks.prototype.execute@moz-extension://3780181e-a070-4655-8b7f-22c497de2afc/userscripts/4chan%20X.user.js?id=98594ecb-4dc5-4f06-bcf9-b7154d0c51f1:5998:17
callbackNodes@moz-extension://3780181e-a070-4655-8b7f-22c497de2afc/userscripts/4chan%20X.user.js?id=98594ecb-4dc5-4f06-bcf9-b7154d0c51f1:28000:12
buildThreads@moz-extension://3780181e-a070-4655-8b7f-22c497de2afc/userscripts/4chan%20X.user.js?id=98594ecb-4dc5-4f06-bcf9-b7154d0c51f1:12236:12
buildCatalogPart@moz-extension://3780181e-a070-4655-8b7f-22c497de2afc/userscripts/4chan%20X.user.js?id=98594ecb-4dc5-4f06-bcf9-b7154d0c51f1:12512:23
fn@moz-extension://3780181e-a070-4655-8b7f-22c497de2afc/userscripts/4chan%20X.user.js?id=98594ecb-4dc5-4f06-bcf9-b7154d0c51f1:12497:23
execTask@moz-extension://3780181e-a070-4655-8b7f-22c497de2afc/userscripts/4chan%20X.user.js?id=98594ecb-4dc5-4f06-bcf9-b7154d0c51f1:5291:19
```

Then from #2666, #2792, #2896, #2930, #3013, #3093, #3106, this issue (YouTube):

2896 "failing" at: `<blockquote class="postMessage" id="m32151892"><a class="linkify youtube" rel="noreferrer noopener" target="_blank" href="https://www.youtube.com/watch?v=pH7WoiAi_6Q&amp;ab_channel=KanataCh.%E5%A4%A9%E9%9F%B3%E3%81%8B%E3%81%AA%E3%81%9F">https://www.youtube.com/watch?v=pH7<wbr>WoiAi_6Q&amp;ab_channel=KanataCh.%E5%A4<wbr>%A9%E9%9F%B3%E3%81%8B%E3%81%AA%E3%8<wbr>1%9F</a> <a class="embedder" href="javascript:;" data-key="YouTube" data-uid="pH7WoiAi_6Q" data-options="&amp;ab_channel=KanataCh.%E5%A4%A9%E9%9F%B3%E3%81%8B%E3%81%AA%E3%81%9F" data-href="https://www.youtube.com/watch?v=pH7WoiAi_6Q&amp;ab_channel=KanataCh.%E5%A4%A9%E9%9F%B3%E3%81%8B%E3%81%AA%E3%81%9F">(<span>un</span>embed)</a></blockquote>`

```
Error: Extension context invalidated.
at chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5638:29
at ajax (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5734:7)
at Function.$.cache (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5026:29)
at Object.cache (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5749:16)
at Object.title (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:16529:28)
at Object.process (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:16431:21)
at Post.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17206:19)
at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5859:17)
at Object.callbackNodes (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:27858:12)
at Object.parse (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:21303:14)
```

and

```
Error: Extension context invalidated.
at chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5646:29
at ajax (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5742:7)
at Function.$.cache (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5026:29)
at Object.cache (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5757:16)
at Object.title (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:16551:28)
at Object.process (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:16453:21)
at Post.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17228:19)
at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5867:17)
at Object.callbackNodes (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:27880:12)
at Object.buildThreads (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:12134:12)
```
