### ISSUE TITLE
Detect multiple instances of 4chan X (was: "Reply Hiding" crashed on node Post No.49859453 (g).)

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#462]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.9.4 crx
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2482.0 Safari/537.36
URL: http://boards.4chan.org/g/thread/49859385

TypeError: Cannot read property 'firstChild' of null
at PostHiding.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5355:27)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1052:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17389:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17393:16)
    at Object.Main.callbackNodesDB (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17404:14)
    at Object.Main.initThread (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17360:21)
    at Main.initReady (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17310:14)
    at HTMLDocument.cb (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:435:14)

**Comment by ccd0** [comment]
This is most likely caused by having multiple versions of 4chan X enabled at once.

**Comment by ccd0** [comment]
This can also cause Quick Reply dialog crashes: #571, #630, #684
More Reply Hiding crashes (two scripts attempting to remove the side arrows): #683, #687, #688

**Comment by ccd0** [comment]
Another instance (reply hiding): #689

**Comment by ccd0** [comment]
#720

**Comment by ccd0** [comment]
#722

**Comment by ccd0** [comment]
#729

**Comment by ccd0** [comment]
From #721.
I was able to reproduce with 4chan X and Appchan X running.

[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.21.5 crx
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
URL: http://boards.4chan.org/b/thread/663103465

TypeError: Cannot read property 'insertBefore' of null
at Function.$.prepend (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:743:18)
at Post.FileInfo.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:15335:9)
at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1107:17)
at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17820:13)
at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17824:16)
