### ISSUE TITLE
"Reply Hiding" crashed on node Post No.7531856 (gif).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#519]
Submitter: fugg
Email: jordywilliem@gmail.com
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.12.6 crx
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
URL: http://boards.4chan.org/gif/thread/7531742

TypeError: Cannot read property 'firstChild' of null
at PostHiding.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5363:27)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1053:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17486:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17490:16)
    at Object.Main.callbackNodesDB (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17501:14)
    at Object.Main.initThread (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17457:21)
    at Function.Main.initReady (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17407:14)
    at MessagePort.$.queueTask.execTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:797:19)

**Comment by ccd0** [comment]
Make sure you don't have two versions of 4chan X / Appchan X enabled at the same time.
