### ISSUE TITLE
"Reply Hiding" crashed on node Post No.51100386 (g).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#558]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.14.9 crx
User agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
URL: http://boards.4chan.org/g/thread/51100300

TypeError: Cannot read property 'firstChild' of null
at PostHiding.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5380:27)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1060:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17502:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17506:16)
    at Object.Main.callbackNodesDB (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17517:14)
    at Object.Main.initThread (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17473:21)
    at Main.initReady (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17423:14)
    at HTMLDocument.cb (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:439:14)

**Comment by ccd0** [comment]
Make sure you only have one copy of 4chan X running at once. #462
