### ISSUE TITLE
Error reporting should check for 4chan x v2 running (was: "File Info Formatting" crashed on node Post No.134811458 (a).)

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#676]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.20.4 userscript
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0
URL: http://boards.4chan.org/a/thread/134811079

HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy
$.add@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:773:12
FileInfo.node@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:15447:1
Callbacks.prototype.execute@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:1216:13
Main.callbackNodesDB/fn@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:17926:9
Main.callbackNodesDB/softTask@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:17930:16
Main.callbackNodesDB@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:17941:14
Main.initThread@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:17897:16
Main.initReady@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:17855:16
$.ready/cb@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:495:14

**Comment by ccd0** [comment]
Can't reproduce this.  Did this happen just once or regularly?  Are you using any other extensions?  If so, can you try turning them off temporarily and turning them back on one by one to identify the one causing the conflict?

(It's okay to make another issue if you don't want to make a throwaway Github account.)

**Comment by ccd0** [comment]
From #702:

[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.21.4 crx
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
URL: https://boards.4chan.org/cm/thread/3000054#p3003489

HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
Error: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
at Error (native)
at Function.$.add (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:739:19)
at Post.FileInfo.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:15336:9)
at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1107:17)
at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17820:13)
at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17824:16)
at Object.Main.callbackNodesDB (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17835:14)
at Object.Main.initThread (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17791:21)
at Main.initReady (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17749:21)
at HTMLDocument.cb (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:461:14)

**Comment by ccd0** [comment]
Not sure what is causing this conflict, but the last error gives enough info to fix it. Something else is removing the "File:" before the link.

**Comment by ccd0** [comment]
It could be someone trying to run two different versions of 4chan X, though.  Probably worth finding out what's causing it before adding complexity to fix this.

**Comment by ccd0** [comment]
Another instance: #708

**Comment by ccd0** [comment]
#782

**Comment by ccd0** [comment]
Based on #919 this appears to be due to people simultaneously running both this 4chan X and loadletter's or some other v2:

> Submitter: lulu
> Email: lulu@lulu.com
> Open a thread, get crash.
> 
> Script: 4chan X ccd0 v1.11.33.4 userscript
> User agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0
> URL: http://boards.4chan.org/fa/thread/11307311
> 
> HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy
> $</$.add@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:4188:12
> FileInfo</FileInfo.node@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:14776:7
> Callbacks</Callbacks.prototype.execute@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:4799:13
> Main</Main.callbackNodesDB/fn@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:22646:9
> Main</Main.callbackNodesDB/softTask@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:22650:16
> Main</Main.callbackNodesDB@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:22661:14
> Main</Main.initThread@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:22615:16
> Main</Main.initReady@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:22560:16
> $</$.ready/cb@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:3900:14
> 
> `<div data-full-i-d="fa.11307311" class="postContainer opContainer" id="pc11307311"><div id="p11307311" class="post op"><div class="postInfoM mobile" id="pim11307311"><span class="nameBlock"><span class="name">Anonymous</span><br><span class="subject">before/after thread?</span> </span><span class="dateTime postNum" data-utc="1463722287">05/20/16(Fri)01:31:27 <a href="#p11307311" title="Link to this post">No.</a><a href="javascript:quote('11307311');" title="Reply to this post">11307311</a></span></div><div class="file" id="f11307311"><div class="fileText" id="fT11307311">&nbsp;<a href="http://iqdb.org/?url=http://i.4cdn.org/fa/1463722287443s.jpg" target="_blank">iqdb</a>&nbsp;<a href="http://www.google.com/searchbyimage?image_url=http://i.4cdn.org/fa/1463722287443s.jpg" target="_blank">google</a></div><a class="fileThumb" href="//i.4cdn.org/fa/1463722287443.jpg" target="_blank"><img src="//i.4cdn.org/fa/1463722287443s.jpg" alt="164 KB" data-md5="698kUIT9M5t24jwm6L1D8g==" style="height: 183px; width: 250px;"><div data-tip="" data-tip-cb="mShowFull" class="mFileInfo mobile">164 KB JPG</div></a></div><div class="postInfo desktop" id="pi11307311"><input name="11307311" value="delete" type="checkbox"> <span class="subject">before/after thread?</span> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span class="dateTime" data-utc="1463722287">05/20/16(Fri)07:31:27</span> <span class="postNum desktop"><a href="#p11307311" title="Link to this post">No.</a><a href="javascript:quote('11307311');" title="Reply to this post">11307311</a></span>&nbsp;<a href="javascript:;" class="menu_button">[<span></span>]</a><a href="javascript:;" class="menu-button"><i class="fa fa-angle-down"></i></a><span class="container"></span></div><blockquote class="postMessage" id="m11307311">before (3-4 yrs ago) <br>after (ytd)</blockquote></div></div>`

v2 menu:
> `<a href="javascript:;" class="menu_button">[<span></span>]</a>`

this script's menu:
> `<a href="javascript:;" class="menu-button"><i class="fa fa-angle-down"></i></a>`

The current test for another copy of 4chan X doesn't catch v2, so I'll need to add a test to the error-handling routine.

**Comment by ccd0** [comment]
#957

**Comment by ccd0** [comment]
Should be fixed now.
