### ISSUE TITLE
"Quote Inlining" crashed on node Post No.51948409 (g).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#682]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.21.3 crx
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
URL: http://boards.4chan.org/g/thread/51948239

TypeError: Cannot read property '0' of null
at QuoteInline.process (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6230:79)
    at Clone.QuoteInline.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6226:9)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1107:17)
    at Object.Main.callbackNodes (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17808:12)
    at Fetcher.insert (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:2230:12)
    at new Fetcher (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:2209:14)
    at HTMLAnchorElement.QuotePreview.mouseover (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6405:7)

**Comment by ccd0** [comment]
Are you using any other extensions?  It's okay to open another report to reply.

**Comment by Mudrock1** [comment]
Personally, my problem with quote inlining is that it just seems to flat out not work. In the past, I usually got notifications about a crash, but in this case it just takes me to the previous post and that's the end of it. It's a fresh install of the script, too. 

Not much else I can provide other than by saying I don't get errors, and that it doesn't seem to affect everybody. 

Firefox 41, most recent version of Greasemonkey.

**Comment by ccd0** [comment]
@Mudrock1
I recently changed the default to only inlining cross-thread links.  If you want to inline all links, you can turn that option off in your settings.

**Comment by Mudrock1** [comment]
@ccd0 
Oh geez. I completely glossed over that and I scrolled over it so many times. 

Cheers, ccd0. Appreciate all the work you do.

**Comment by ccd0** [comment]
From #699:

Submitter: Anonymous Pizza Guy
Email: millerlite2006@gmail.com
[Please describe the steps needed to reproduce this error.] Go on any thread with 4chanx enabled

Script: 4chan X ccd0 v1.11.21.4 crx
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
URL: http://boards.4chan.org/v/thread/321203720

TypeError: Cannot read property '0' of null
at QuoteInline.process (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6230:79)
at Post.QuoteInline.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6226:9)
at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1107:17)
at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17820:13)
at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17824:16)

**Comment by ccd0** [comment]
Another instance: #682

**Comment by ccd0** [comment]
#736

**Comment by ccd0** [comment]
I never did find out what caused this, but the code that was crashing has since been changed for other reasons.
