### ISSUE TITLE
"Reply Hiding" crashed on node Post No.320937813 (v).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#683]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.21.3 crx
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/44.0.2403.89 Chrome/44.0.2403.89 Safari/537.36
URL: http://boards.4chan.org/v/thread/320936868

TypeError: Cannot read property 'firstChild' of null
at PostHiding.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5465:27)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1107:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17820:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17824:16)
    at Object.Main.callbackNodesDB (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17835:14)
    at Object.Main.initThread (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17791:21)
    at Main.initReady (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17749:21)
    at HTMLDocument.cb (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:461:14)

**Comment by ccd0** [comment]
Make sure you only have one copy of 4chan X enabled.
