### ISSUE TITLE
"Reply Hiding" crashed on node Post No.63935625 (tv).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#688]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.21.4 crx
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
URL: http://boards.4chan.org/tv/thread/63934642

TypeError: Cannot read property 'firstChild' of null
at PostHiding.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5465:27)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1107:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17820:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17824:16)

**Comment by ccd0** [comment]
Make sure you only have one copy of 4chan X enabled.
