### ISSUE TITLE
"Quote Inlining" crashed on node Post No.321206215 (v).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#699]
Submitter: Anonymous Pizza Guy
Email: millerlite2006@gmail.com
[Please describe the steps needed to reproduce this error.] Go on any thread with 4chanx enabled

Script: 4chan X ccd0 v1.11.21.4 crx
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
URL: http://boards.4chan.org/v/thread/321203720

TypeError: Cannot read property '0' of null
at QuoteInline.process (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6230:79)
    at Post.QuoteInline.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6226:9)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1107:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17820:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17824:16)

**Comment by ccd0** [comment]
Are you using any other extensions? Have you tried disabling them, and if that fixes it, turning them back on one by one?

**Comment by ccd0** [comment]
Merging into #682.
