### ISSUE TITLE
"Quote Inlining" crashed on node Post No.135567608 (a).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#712]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.21.5 crx
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
URL: http://boards.4chan.org/a/thread/135566508

TypeError: Cannot read property '0' of null
at QuoteInline.process (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6230:79)
    at Clone.QuoteInline.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6226:9)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1107:17)
    at Object.Main.callbackNodes (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17808:12)
    at Fetcher.insert (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:2230:12)
    at new Fetcher (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:2209:14)
    at HTMLAnchorElement.QuotePreview.mouseover (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6405:7)

**Comment by ccd0** [comment]
Are you using any other extensions? Have you tried disabling them, and if that fixes it, turning them back on one by one?
