### ISSUE TITLE
"File Info Formatting" crashed on node Post No.663112352 (b).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#721]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.21.5 crx
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
URL: http://boards.4chan.org/b/thread/663103465

TypeError: Cannot read property 'insertBefore' of null
at Function.$.prepend (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:743:18)
    at Post.FileInfo.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:15335:9)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1107:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17820:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17824:16)

**Comment by ccd0** [comment]
Are you using any other extensions / userscripts besides 4chan X that might be causing a conflict? Can you check if temporarily disabling other extensions makes the issue go away? It's okay to open another issue to respond; I'll merge it into this one.

**Comment by ccd0** [comment]
This is most likely due to having multiple copies of 4chan X / Appchan X enabled.
