### ISSUE TITLE
"Reply Hiding" crashed on node Post No.128254480 (vg).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#722]
Submitter: Anon
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.21.5 crx
User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
URL: http://boards.4chan.org/vg/thread/128247681

TypeError: Cannot read property 'firstChild' of null
at PostHiding.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5465:27)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1107:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17820:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17824:16)

**Comment by ccd0** [comment]
You have more than one copy of 4chan X enabled.
