### ISSUE TITLE
"Relative Post Dates" crashed on node Post No.63523854 (pol).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#766]
Submitter: cami
Email: camig209@gmail.com
[I tried to insert a link to /pol/ on my quick bar. Before it was : 

~*~*~
[ ck-title /
tv-title ]
~*~*~
[ g-replace
/ v-replace
/ cgl-replace
/ fit-replace
/ mu-replace
/ sp-replace
 ]
~*~*~
[toggle-all]
~*~*~]

I changed it to 

~*~*~
[ ck-title /
tv-title ]
~*~*~
[ g-replace
/ v-replace
/ cgl-replace
/ fit-replace
/ mu-replace
/ sp-replace
/ pol-replace ]
~*~*~
[toggle-all]
~*~*~

And now when I click /pol/ all these errors load up. Note I go straight to catalog. I might do pol-title now, maybe that will fix it. ok bye ]

Script: 4chan X ccd0 v1.11.24.1 crx
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2643.0 Safari/537.36
URL: http://boards.4chan.org/pol/

TypeError: Cannot set property 'textContent' of null
at Object.RelativeDates.update (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:16465:56)
    at Post.RelativeDates.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:16420:28)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1118:17)
    at Object.Main.callbackNodes (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17991:12)
    at Object.Index.buildThreads (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:3863:12)
    at Object.Index.parse (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:3799:13)
    at XMLHttpRequest.Index.load (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:3765:17)

**Comment by ccd0** [comment]
Assuming the problem is still happening, are you using any other extensions besides 4chan X?
