### ISSUE TITLE
"Image Expansion" crashed on node Post No.861089 (his).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#812]
Email: braedan00@gmail.com
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.27.2 crx
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
URL: http://boards.4chan.org/his/thread/860974

TypeError: Cannot read property 'parentNode' of null
at Clone.ImageExpand.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:10716:27)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1125:17)
    at Object.Main.callbackNodes (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:18095:12)
    at Fetcher.insert (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:2250:12)
    at new Fetcher (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:2229:14)
    at HTMLAnchorElement.QuotePreview.mouseover (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6425:7)

**Comment by ccd0** [comment]
Are you using any other extensions? What were you doing when this error happened?
