### ISSUE TITLE
"File Info Formatting" crashed on node Post No.82283854 (co).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#858]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.31.3 crx
User agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
URL: http://boards.4chan.org/co/thread/82276059#p82292467

TypeError: Cannot read property 'insertBefore' of null
at Function.$.prepend (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4109:18)
    at Post.FileInfo.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:14566:9)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4645:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22421:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22425:16)

**Comment by ccd0** [comment]
Are you using any other extensions? You can open another issue to answer if you don't want to make an account.

**Comment by ccd0** [comment]
#859 #860

**Comment by ccd0** [comment]
#863 #870 #871

**Comment by ccd0** [comment]
#872

**Comment by ccd0** [comment]
#875

**Comment by ccd0** [comment]
From #877:
> I solved it by uninstalling the extension, then uninstalling the following extensions:
> Kappa Everywhere
> Emoji Stuff
> SJW to Skeleton
> and some extension that lets you view Dota 2 emoticons if someone types them in.
> 
> I then reinstalled 4chan x and it's working fine now.

**Comment by ccd0** [comment]
Looks like
https://chrome.google.com/webstore/detail/emoji-input-by-emojistuff/immhpnclomdloikkpcefncmfgjbkojmh
is the culprit.

**Comment by ccd0** [comment]
First occurrence seems to coincide with the time people started complaining about the latest version breaking sites on their support page, too:

https://chrome.google.com/webstore/detail/emoji-input-by-emojistuff/immhpnclomdloikkpcefncmfgjbkojmh/support

**Comment by ccd0** [comment]
QUALITY

    function showEmoji(nodes) {
      var googleReplaced = replaceGoogleEmojiWithTextEmoji();
      var twitterReplaced = replaceTwitterEmojiWithTextEmoji();

      if (googleReplaced == true) { //|| twitterReplaced.length > 0
        showEmoji(filterNodes('body *:not(iframe)'));
        return false;
      }

      $.each(nodes, function () {

        var $this = $(this);

        if ($this.attr('contenteditable') == 'true') return true;
        if ($this.attr('contenteditable') == 'plaintext-only') return true;
        if ($this.text().trim().length < 1) return true;
        if ($this.parents("[contenteditable='true']").length !== 0) return true;

        var textToCheck = $this.text().replace(/&amp;/g, '&').replace(/&/g, '&amp;');
        var modifiedText = textToCheck;
        var emojiExist = false;

        if (modifiedText.length > 0) {
          modifiedText = emoji.replace_unified(modifiedText);
          emojiExist = true;
        }

        if (emojiExist === true) {

          var $node = $this[0].parentElement;

          if ($node == undefined) $node = $this.parents()[0];
          if ($node == undefined) $node = $this.parents()[1];
          if ($node == undefined) $node = $this.parents()[2];
          if ($node == undefined) $node = $this.parents()[3];

          if ($node) {
            var html = $node.innerHTML;
            if (html.toLowerCase().indexOf('document.write') === -1) {
              html = html.replace(/”/g, '&rdquo;');
              var replace = html.replace(textToCheck.replace(/\xa0/g, '&nbsp;').replace(/”/g, '&rdquo;'), modifiedText);
              $node.innerHTML = replace;
            }
          }

          addStyleSheet();
        }

      });

      if (twitterReplaced.length > 0) showEmoji(filterNodes('body *:not(iframe)'));

    }

**Comment by ccd0** [comment]
Complete with phone-home code:

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-46232748-1']);
    _gaq.push(['_setSampleRate', '20']);

    (function () {
      var ga = document.createElement('script');
      ga.type = 'text/javascript';
      ga.async = true;
      ga.src = 'https://ssl.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(ga, s);
    })();

    chrome.runtime.onMessage.addListener(
      function (request, sender, sendResponse) {

        _gaq.push(['_trackEvent', request.eventtype, request.emoji, request.site]);

      });

**Comment by ccd0** [comment]
I've added notes to the bug report pages.
