### ISSUE TITLE
"Quote Inlining" crashed on node Post No.54287997 (g). (+1 other errors)

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#861]
[Please describe the steps needed to reproduce this error.]
No steps, appeared randomly

Script: 4chan X ccd0 v1.11.31.3 crx
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
URL: https://boards.4chan.org/g/thread/54276467#p54277852

TypeError: Cannot read property 'insertBefore' of null
at Function.$.after (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4113:27)
    at QuoteInline.process (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:21286:13)
    at Post.QuoteInline.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:21275:9)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4645:17)
    at fn (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22421:13)
    at softTask (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22425:16)

**Comment by ccd0** [comment]
Are you using any other extensions? You can open another issue to answer if you don't want to register a Github account.
