### ISSUE TITLE
"Quote Threading" crashed on node Post No.3938098 (trash).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#988]
Submitter: Leroy Brown
Email: Catalyst1259@aol.com
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.12.0.8 crx
User agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.154 Safari/537.36
URL: http://boards.4chan.org/trash/thread/3934999#p3934999

ReferenceError: Set is not defined
at Post.QuoteThreading.node (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:21762:21)
    at Callbacks.execute (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4676:17)
    at Object.Main.callbackNodes (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:22610:12)
    at Object.ThreadUpdater.parse (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:17031:14)
    at XMLHttpRequest.ThreadUpdater.cb.load (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:16819:27)

`<div class="postContainer replyContainer" id="pc3938098" data-full-i-d="trash.3938098"><div class="sideArrows" id="sa3938098">&gt;&gt;</div><div id="p3938098" class="post reply"><div class="postInfo desktop" id="pi3938098"><input type="checkbox" name="3938098" value="delete"> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span class="dateTime" data-utc="1467865835">07/07/16(Thu)00:30:35</span> <span class="postNum desktop"><a href="#p3938098" title="Link to this post">No.</a><a href="javascript:quote('3938098');" title="Reply to this post">3938098</a></span><a class="menu-button" href="javascript:;"><i class="fa fa-angle-down"></i></a><span class="container"></span></div><div class="file" id="f3938098"><div class="fileText" id="fT3938098">File: <a href="//i.4cdn.org/trash/1467865835038.jpg" target="_blank">Descendents_MiloGoesToCollege.jpg</a> (70 KB, 700x695) <a target="_blank" class="sauce" href="https://www.google.com/searchbyimage?image_url=http%3A%2F%2Fi.4cdn.org%2Ftrash%2F1467865835038.jpg&amp;safe=off">google</a> <a target="_blank" class="sauce"></a> <a target="_blank" class="sauce" href="//iqdb.org/?url=http%3A%2F%2Fi.4cdn.org%2Ftrash%2F1467865835038.jpg">iqdb</a> <a target="_blank" class="sauce" href="https://whatanime.ga/?auto&amp;url=http%3A%2F%2Fi.4cdn.org%2Ftrash%2F1467865835038.jpg">wait</a> <a target="_blank" class="sauce"></a> <a target="_blank" class="sauce"></a> <a target="_blank" class="sauce"></a></div><a class="fileThumb" href="//i.4cdn.org/trash/1467865835038.jpg" target="_blank"><img src="//i.4cdn.org/trash/1467865835038s.jpg" alt="70 KB" data-md5="fPXPEXrHqhfAZp+Ai/JcRw==" style="height: 124px; width: 125px;"></a></div><blockquote class="postMessage" id="m3938098"><a href="#p3937987" class="quotelink">&gt;&gt;3937987</a><br>This with Lisa</blockquote></div></div>`

**Comment by ccd0** [comment]
Your browser is out of date, and new versions of 4chan X will not work with it.

**Comment by ccd0** [comment]
These particular changes have been reverted for now, but you should still update your browser as soon as possible.
